In [3]:
import numpy as np
an_array = np.array([3, 33, 333])
print(type(an_array))

<class 'numpy.ndarray'>


In [7]:
print(an_array.shape)

(3,)


In [13]:
an_array[0] = 888
print(an_array)    # mutable

[888  33 333]


In [31]:
another = np.array([[11, 12, 13], [21, 22, 23]])
print(another)
print('shape:2 rows ,3 columns:')
print(another.shape)

[[11 12 13]
 [21 22 23]]
shape:2 rows ,3 columns:
(2, 3)


In [34]:
import numpy as np
exp1 = np.zeros((2, 2))
print(exp1)

[[ 0.  0.]
 [ 0.  0.]]


In [36]:
exp2 = np.full((2, 2), 4.5)
print(exp2)

[[ 4.5  4.5]
 [ 4.5  4.5]]


In [38]:
exp3 = np.eye(2, 2)
print(exp3)

[[ 1.  0.]
 [ 0.  1.]]


In [39]:
exp4 = np.ones((1, 2))
print(exp4)

[[ 1.  1.]]


In [49]:
exp5 = np.random.random((2, 2))
print(exp5)

[[ 0.33231676  0.31178743]
 [ 0.62128837  0.80553855]]


In [8]:
import numpy as np
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
fil = (an_array > 15)
print(fil)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [9]:
print(an_array[fil])

[21 22 23 31 32 33]


In [13]:
an_array[(an_array % 2 == 0)] += 100
print(an_array)

[[ 11 112  13]
 [ 21 122  23]
 [ 31 132  33]]


In [15]:
arr = np.array([2.3, 4.4], dtype=np.int64)
print(arr)

[2 4]


In [16]:
x = np.array([2.3, 4.4])
y = np.array([2, 4])
print(x + y)
print()
print(np.add(x, y))

[ 4.3  8.4]

[ 4.3  8.4]


In [2]:
import numpy as np
arr = 10 * np.random.randn(2, 5)
print(arr)

[[  2.43174779   5.04618076   3.18462928 -23.73062982   1.35753365]
 [  9.92850728   3.70592699  -7.57894459  -7.15497862   1.02522144]]


In [3]:
print(arr.mean())

-1.17848058197


In [4]:
print(arr.mean(axis=1))  # by rows

[-2.34210767 -0.0148535 ]


In [5]:
print(arr.mean(axis=0))  # by column

[  6.18012754   4.37605388  -2.19715765 -15.44280422   1.19137755]


In [7]:
print(np.median(arr, axis=1))  # by rows

[ 2.43174779  1.02522144]


In [9]:
unsorted = np.random.randn(10)
print(unsorted)

[ 1.85463038  1.02687716 -0.61562789  0.5545693   0.54490149  1.00542596
  0.43767678  0.02239573 -0.95348457  1.74975168]


In [10]:
sorted = np.array(unsorted)
sorted.sort()
print(sorted)

[-0.95348457 -0.61562789  0.02239573  0.43767678  0.54490149  0.5545693
  1.00542596  1.02687716  1.74975168  1.85463038]


In [12]:
unsorted.sort()
print(unsorted)

[-0.95348457 -0.61562789  0.02239573  0.43767678  0.54490149  0.5545693
  1.00542596  1.02687716  1.74975168  1.85463038]


In [13]:
array = np.array([1, 2, 4, 2, 1, 4, 2, 2, 1])
print(np.unique(array))


[1 2 4]


In [15]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])
print(np.union1d(a, b))

[1 2 3 4 5]


In [16]:
print(np.intersect1d(a, b))


[3]


In [17]:
print(np.setdiff1d(a, b))  # a - b

[1 2]


In [18]:
print(np.in1d(a, b))

[False False  True]


In [19]:
start = np.zeros((3, 3))
print(start)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [25]:
add_rows = np.array([0, 1, 2])
add_cols = np.array([[0], [1], [2]])
add_scalar = np.array([110])
print(add_rows)
print()
print(add_cols)
print()
print(add_scalar)


[0 1 2]

[[0]
 [1]
 [2]]

[110]


In [26]:
print(start + add_rows)  # broadcasting
print()
print(start + add_cols) 
print()
print(start + add_scalar)


[[ 0.  1.  2.]
 [ 0.  1.  2.]
 [ 0.  1.  2.]]

[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]]

[[ 110.  110.  110.]
 [ 110.  110.  110.]
 [ 110.  110.  110.]]


In [27]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits = 1000

In [28]:
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [ ]:
timer_numpy = Timer("nd_array.sum()", "from__main__import nd_array")
print("Time taken by numpy nd_array: %f seconds" % (timer_numpy.timeit(timeits)/timeits))